[package]
name = "mdbook-i18n-helpers"
version = "0.1.0"
authors = ["Martin Geisler <mgeisler@google.com>"]
categories = ["command-line-utilities", "localization"]
edition = "2021"
keywords = ["mdbook", "i18n", "translation", "gettext"]
license = "Apache-2.0"
repository = "https://github.com/google/mdbook-i18n-helpers"
description = "Helpers for a mdbook i18n workflow based on Gettext."

[dependencies]
anyhow = "1.0.68"
mdbook = "0.4.25"
polib = "0.2.0"
pulldown-cmark = { version = "0.9.2", default-features = false }
semver = "1.0.16"
serde_json = "1.0.91"
toml = "0.5.1"
